//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CambioDeMonedaExchagePetition", ReplyAction="http://tempuri.org/IService1/CambioDeMonedaExchagePetitionResponse")]
        WcfServiceLibrary1.ExchagePetition CambioDeMonedaExchagePetition(WcfServiceLibrary1.ExchagePetition petition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CambioDeMonedaExchagePetition", ReplyAction="http://tempuri.org/IService1/CambioDeMonedaExchagePetitionResponse")]
        System.Threading.Tasks.Task<WcfServiceLibrary1.ExchagePetition> CambioDeMonedaExchagePetitionAsync(WcfServiceLibrary1.ExchagePetition petition);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CambioDeMoneda", ReplyAction="http://tempuri.org/IService1/CambioDeMonedaResponse")]
        decimal CambioDeMoneda(string MonedaOrigen, string MonedaDestino, decimal Monto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CambioDeMoneda", ReplyAction="http://tempuri.org/IService1/CambioDeMonedaResponse")]
        System.Threading.Tasks.Task<decimal> CambioDeMonedaAsync(string MonedaOrigen, string MonedaDestino, decimal Monto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WindowsFormsApp1.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WindowsFormsApp1.ServiceReference1.IService1>, WindowsFormsApp1.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WcfServiceLibrary1.ExchagePetition CambioDeMonedaExchagePetition(WcfServiceLibrary1.ExchagePetition petition) {
            return base.Channel.CambioDeMonedaExchagePetition(petition);
        }
        
        public System.Threading.Tasks.Task<WcfServiceLibrary1.ExchagePetition> CambioDeMonedaExchagePetitionAsync(WcfServiceLibrary1.ExchagePetition petition) {
            return base.Channel.CambioDeMonedaExchagePetitionAsync(petition);
        }
        
        public decimal CambioDeMoneda(string MonedaOrigen, string MonedaDestino, decimal Monto) {
            return base.Channel.CambioDeMoneda(MonedaOrigen, MonedaDestino, Monto);
        }
        
        public System.Threading.Tasks.Task<decimal> CambioDeMonedaAsync(string MonedaOrigen, string MonedaDestino, decimal Monto) {
            return base.Channel.CambioDeMonedaAsync(MonedaOrigen, MonedaDestino, Monto);
        }
    }
}
